const notifications = [
    {
        pk: 1,
        url: "http://localhost:8000/notification/45/detail/?format=json",
        message: "New activity added by: code",
        status: 0,
        created_at: "2024-02-22T02:29:50.680189Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/activity/67/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 2,
        url: "http://localhost:8000/notification/48/detail/?format=json",
        message: "New activity added by: EMOER24E1",
        status: 0,
        created_at: "2024-02-22T02:30:39.414138Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/activity/68/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 3,
        url: "http://localhost:8000/notification/22/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 0,
        created_at: "2024-02-21T14:19:55.578247Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/67/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 4,
        url: "http://localhost:8000/notification/24/detail/?format=json",
        message: "New activity added",
        status: 0,
        created_at: "2024-02-21T21:11:26.579860Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/activity/58/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 5,
        url: "http://localhost:8000/notification/76/detail/?format=json",
        message: "New goal added by: EMOER24E1",
        status: 0,
        created_at: "2024-02-22T09:04:59.987901Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/goal/42/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 6,
        url: "http://localhost:8000/notification/79/detail/?format=json",
        message: "New task added.",
        status: 0,
        created_at: "2024-02-22T11:45:13.214504Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/69/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 7,
        url: "http://localhost:8000/notification/81/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 0,
        created_at: "2024-02-22T11:48:02.340270Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/68/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 8,
        url: "http://localhost:8000/notification/83/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 0,
        created_at: "2024-02-22T16:07:44.199406Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/69/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 9,
        url: "http://localhost:8000/notification/42/detail/?format=json",
        message: "New activity added by",
        status: 1,
        created_at: "2024-02-22T02:24:08.306467Z",
        read_at: "2024-02-28T09:32:06.714989Z",
        is_deleted: true,
        target: "/tasks/activity/66/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 10,
        url: "http://localhost:8000/notification/85/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 0,
        created_at: "2024-02-22T16:08:05.553346Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/67/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 11,
        url: "http://localhost:8000/notification/87/detail/?format=json",
        message: "target TEST 23 completed.",
        status: 0,
        created_at: "2024-02-22T16:08:05.598610Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/goal/25/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 12,
        url: "http://localhost:8000/notification/91/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 0,
        created_at: "2024-02-22T16:10:21.660904Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/69/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 13,
        url: "http://localhost:8000/notification/95/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 1,
        created_at: "2024-02-22T16:11:18.088318Z",
        read_at: "2024-02-28T09:31:22.803912Z",
        is_deleted: true,
        target: "/tasks/report/70/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 14,
        url: "http://localhost:8000/notification/93/detail/?format=json",
        message: "New task added.",
        status: 1,
        created_at: "2024-02-22T16:10:56.964056Z",
        read_at: "2024-02-28T09:31:34.228334Z",
        is_deleted: true,
        target: "/tasks/report/70/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 15,
        url: "http://localhost:8000/notification/97/detail/?format=json",
        message: "New task added.",
        status: 0,
        created_at: "2024-03-08T11:05:35.363947Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/73/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 16,
        url: "http://localhost:8000/notification/45/detail/?format=json",
        message: "New activity added by: code",
        status: 0,
        created_at: "2024-02-22T02:29:50.680189Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/activity/67/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 17,
        url: "http://localhost:8000/notification/48/detail/?format=json",
        message: "New activity added by: EMOER24E1",
        status: 0,
        created_at: "2024-02-22T02:30:39.414138Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/activity/68/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 18,
        url: "http://localhost:8000/notification/22/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 0,
        created_at: "2024-02-21T14:19:55.578247Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/67/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 19,
        url: "http://localhost:8000/notification/24/detail/?format=json",
        message: "New activity added",
        status: 0,
        created_at: "2024-02-21T21:11:26.579860Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/activity/58/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 20,
        url: "http://localhost:8000/notification/76/detail/?format=json",
        message: "New goal added by: EMOER24E1",
        status: 0,
        created_at: "2024-02-22T09:04:59.987901Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/goal/42/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 21,
        url: "http://localhost:8000/notification/79/detail/?format=json",
        message: "New task added.",
        status: 0,
        created_at: "2024-02-22T11:45:13.214504Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/69/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 22,
        url: "http://localhost:8000/notification/81/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 0,
        created_at: "2024-02-22T11:48:02.340270Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/68/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 23,
        url: "http://localhost:8000/notification/83/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 0,
        created_at: "2024-02-22T16:07:44.199406Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/69/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 24,
        url: "http://localhost:8000/notification/85/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 0,
        created_at: "2024-02-22T16:08:05.553346Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/67/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 25,
        url: "http://localhost:8000/notification/87/detail/?format=json",
        message: "target TEST 23 completed.",
        status: 0,
        created_at: "2024-02-22T16:08:05.598610Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/goal/25/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 26,
        url: "http://localhost:8000/notification/91/detail/?format=json",
        message: "report updated. REJECTED!",
        status: 0,
        created_at: "2024-02-22T16:10:21.660904Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/69/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    },
    {
        pk: 27,
        url: "http://localhost:8000/notification/97/detail/?format=json",
        message: "New task added.",
        status: 0,
        created_at: "2024-03-08T11:05:35.363947Z",
        read_at: null,
        is_deleted: true,
        target: "/tasks/report/73/detail/",
        user: "http://localhost:8000/EGT/user/1/detail/?format=json",
        enterprise: "http://localhost:8000/EGT/enterprise/1/detail/?format=json"
    }

]

module.exports = {notifications}